import enum
from datetime import datetime
from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .database import Base
class Role(str,enum.Enum): ADMIN="ADMIN"; MANAGER="MANAGER"; LEAD="LEAD"
class DriveStatus(str,enum.Enum): DRAFT="DRAFT"; OPEN="OPEN"; CLOSED="CLOSED"
class ApplicationStatus(str,enum.Enum): APPLIED="APPLIED"; SHORTLISTED="SHORTLISTED"; INTERVIEW="INTERVIEW"; OFFERED="OFFERED"; REJECTED="REJECTED"; WITHDRAWN="WITHDRAWN"
class RecruiterStatus(str,enum.Enum): HOT="HOT"; WARM="WARM"; COLD="COLD"
class PlacementStatus(str,enum.Enum): SEEKING="SEEKING"; PLACED="PLACED"; NOT_ELIGIBLE="NOT_ELIGIBLE"
class Timestamped:
 created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow,onupdate=datetime.utcnow)
class User(Timestamped,Base):
 __tablename__="users"; id:Mapped[int]=mapped_column(primary_key=True); full_name:Mapped[str]=mapped_column(String(120)); email:Mapped[str]=mapped_column(String(255),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); role:Mapped[Role]=mapped_column(Enum(Role),default=Role.LEAD); is_active:Mapped[bool]=mapped_column(Boolean,default=True)
 created_drives=relationship("PlacementDrive",back_populates="created_by"); team_profile=relationship("PlacementTeamMember",foreign_keys="[PlacementTeamMember.user_id]",back_populates="user",uselist=False); invited_memberships=relationship("PlacementTeamMember",foreign_keys="[PlacementTeamMember.invited_by_id]",back_populates="invited_by"); notifications=relationship("Notification",back_populates="recipient")
class Company(Timestamped,Base):
 __tablename__="companies"; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(160),unique=True,index=True); website:Mapped[str|None]=mapped_column(String(255)); industry:Mapped[str|None]=mapped_column(String(120)); contact_name:Mapped[str|None]=mapped_column(String(120)); contact_email:Mapped[str|None]=mapped_column(String(255)); recruiter_status:Mapped[RecruiterStatus]=mapped_column(Enum(RecruiterStatus),default=RecruiterStatus.COLD,index=True)
 drives=relationship("PlacementDrive",back_populates="company",cascade="all, delete-orphan")
class Student(Timestamped,Base):
 __tablename__="students"; id:Mapped[int]=mapped_column(primary_key=True); registration_number:Mapped[str]=mapped_column(String(80),unique=True,index=True); name:Mapped[str]=mapped_column(String(140)); email:Mapped[str]=mapped_column(String(255),unique=True,index=True); phone:Mapped[str|None]=mapped_column(String(30)); department:Mapped[str]=mapped_column(String(120),index=True); academic_details:Mapped[str|None]=mapped_column(Text); cgpa:Mapped[str|None]=mapped_column(String(20)); skills:Mapped[str|None]=mapped_column(Text); is_eligible:Mapped[bool]=mapped_column(Boolean,default=False,index=True); placement_status:Mapped[PlacementStatus]=mapped_column(Enum(PlacementStatus),default=PlacementStatus.SEEKING,index=True); placed_company_id:Mapped[int|None]=mapped_column(ForeignKey("companies.id")); offer_package_lpa:Mapped[str|None]=mapped_column(String(60)); resume_path:Mapped[str|None]=mapped_column(String(500)); drive_links:Mapped[dict]=mapped_column(JSON,default=list)
 applications=relationship("Application",back_populates="student"); placed_company=relationship("Company")
class PlacementDrive(Timestamped,Base):
 __tablename__="placement_drives"; id:Mapped[int]=mapped_column(primary_key=True); title:Mapped[str]=mapped_column(String(180)); company_id:Mapped[int]=mapped_column(ForeignKey("companies.id")); location:Mapped[str]=mapped_column(String(140)); package_lpa:Mapped[str|None]=mapped_column(String(60)); eligibility:Mapped[str]=mapped_column(Text); deadline:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); status:Mapped[DriveStatus]=mapped_column(Enum(DriveStatus),default=DriveStatus.DRAFT); created_by_id:Mapped[int]=mapped_column(ForeignKey("users.id")); description:Mapped[str|None]=mapped_column(Text); drive_date:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); departments:Mapped[str|None]=mapped_column(Text); required_skills:Mapped[str|None]=mapped_column(Text); work_mode:Mapped[str|None]=mapped_column(String(60)); is_archived:Mapped[bool]=mapped_column(Boolean,default=False,index=True)
 company=relationship("Company",back_populates="drives"); created_by=relationship("User",back_populates="created_drives"); applications=relationship("Application",back_populates="drive",cascade="all, delete-orphan"); team_assignments=relationship("PlacementTeamDriveAssignment",back_populates="drive",cascade="all, delete-orphan")
class Application(Timestamped,Base):
 __tablename__="applications"; __table_args__=(UniqueConstraint("student_id","drive_id",name="uq_student_drive_application"),); id:Mapped[int]=mapped_column(primary_key=True); student_name:Mapped[str]=mapped_column(String(140)); student_email:Mapped[str]=mapped_column(String(255),index=True); student_id:Mapped[int|None]=mapped_column(ForeignKey("students.id"),index=True); drive_id:Mapped[int]=mapped_column(ForeignKey("placement_drives.id")); status:Mapped[ApplicationStatus]=mapped_column(Enum(ApplicationStatus),default=ApplicationStatus.APPLIED); resume_path:Mapped[str|None]=mapped_column(String(500))
 drive=relationship("PlacementDrive",back_populates="applications"); student=relationship("Student",back_populates="applications")
class PlacementTeamMember(Timestamped,Base):
 __tablename__="placement_team_members"; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey("users.id"),unique=True); role:Mapped[str]=mapped_column(String(120),default="Placement Officer",index=True); responsibility:Mapped[str]=mapped_column(String(255)); assignment:Mapped[str|None]=mapped_column(String(255)); department:Mapped[str|None]=mapped_column(String(120)); phone:Mapped[str|None]=mapped_column(String(30)); is_active:Mapped[bool]=mapped_column(Boolean,default=True,index=True); is_team_lead:Mapped[bool]=mapped_column(Boolean,default=False,index=True); joined_date:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),default=datetime.utcnow); invited_by_id:Mapped[int|None]=mapped_column(ForeignKey("users.id")); invitation_status:Mapped[str]=mapped_column(String(30),default="ACTIVE")
 user=relationship("User",foreign_keys=[user_id],back_populates="team_profile"); invited_by=relationship("User",foreign_keys=[invited_by_id],back_populates="invited_memberships"); drive_assignments=relationship("PlacementTeamDriveAssignment",back_populates="team_member",cascade="all, delete-orphan")
class PlacementTeamDriveAssignment(Timestamped,Base):
 __tablename__="placement_team_drive_assignments"; __table_args__=(UniqueConstraint("team_member_id","drive_id",name="uq_team_member_drive_assignment"),)
 id:Mapped[int]=mapped_column(primary_key=True); team_member_id:Mapped[int]=mapped_column(ForeignKey("placement_team_members.id"),index=True); drive_id:Mapped[int]=mapped_column(ForeignKey("placement_drives.id"),index=True); responsibility:Mapped[str|None]=mapped_column(String(120));
 team_member=relationship("PlacementTeamMember",back_populates="drive_assignments"); drive=relationship("PlacementDrive",back_populates="team_assignments")
class Notification(Base):
 __tablename__="notifications"; id:Mapped[int]=mapped_column(primary_key=True); recipient_id:Mapped[int]=mapped_column(ForeignKey("users.id"),index=True); title:Mapped[str]=mapped_column(String(160)); message:Mapped[str]=mapped_column(Text); notification_type:Mapped[str]=mapped_column(String(50)); entity_type:Mapped[str|None]=mapped_column(String(80)); entity_id:Mapped[str|None]=mapped_column(String(80)); is_read:Mapped[bool]=mapped_column(Boolean,default=False,index=True); read_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow,index=True); recipient=relationship("User",back_populates="notifications")
class AuditLog(Base):
 __tablename__="audit_logs"; id:Mapped[int]=mapped_column(primary_key=True); actor_id:Mapped[int|None]=mapped_column(ForeignKey("users.id")); action:Mapped[str]=mapped_column(String(80)); entity_type:Mapped[str]=mapped_column(String(80)); entity_id:Mapped[str]=mapped_column(String(80)); details:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow,index=True)
